### ISSUE TITLE
Choose message broker to use in notifier

### ISSUE THREAD

**Issue by zxcat** [GolosChain/cyberway.notifier#1]

**Comment by zxcat** [comment]
Requirements:
1. At-least-one delivery (reordering allowed)
2. Persistence
3. Node.js lib
4. C++/C lib
5. Micro-service-like solution (lightweight)

**Comment by s-medvedev** [comment]
`nats-streaming` message broker selected

**Comment by zxcat** [comment]
other candidates:
* *kafka* — good, but requires jvm;
* *redis* — looks good, but it's main purpose is not to be broker;
* *nsq* — C library do not looks solid; performance tests worse
* *nats* (pure) — provides only "at-most-once" delivery
* *[liftbridge](https://github.com/liftbridge-io/liftbridge)* — looks very interesting, but not production ready

Others are either do not fit base requirements, or too overloaded (enterprise-like) and expensive to maintain
